api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    enable_docs: true
    enable_swagger_ui: true
    enable_re_doc: true
    graphql:
        enabled: true
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
